version: '3.8'
services:
  app:
    build: .
    container_name: node_app
    ports:
      - '3000:3000'
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=sofcompus
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sofcompus
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d  # Monta el script de inicialización
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
