apiVersion: v1
kind: Service
metadata:
  name: db-sofcompus
spec:
  selector:
    app: mysql-sofcompus
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP  # Modo ClusterIP para que sólo esté disponible dentro del clúster
