apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-sofcompus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-sofcompus
  template:
    metadata:
      labels:
        app: mysql-sofcompus
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "sofcompus"
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        - name: db-init-sofcompus
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc-sofcompus
      - name: db-init-sofcompus
        hostPath:
          path: \db-init-sofcompus\init.sql  # Ruta donde están los scripts de inicialización
