apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-sofcompus  # Para la base de datos `sofcompus`
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-parqueadero  # Para la base de datos `parqueadero`
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
